jobs:
- deployment: job1
  environment: test0706a.default
  pool: default
  strategy:
   runOnce:
    deploy:
     steps:
     - script: echo Hello, world!
       displayName: 'Run a one-line script'
     - task: Kubernetes@1
       displayName: 'kubectl get'
       inputs:        
        namespace: 'default'
        command: get
        arguments: pods